@hostname=localhost
@port=3000

### Get all crypto
GET http://{{hostname}}:{{port}}/api/crypto
Content-Type: "application/json"

### Save crypto as favorite
POST / HTTP/1.1
Host: http://{{hostname}}:{{port}}/api/crypto
Content-Type: "application/json"

{ "id": "ATTA" }

###

### Exchange rates

### Get all currencies
GET http://{{hostname}}:{{port}}/api/rates/exchange-rates
Accept: 'application/json'
Content-Type: 'text/json'

### Add currency
POST http://{{hostname}}:{{port}}/api/rates/exchange-rates
Accept: application/json
Content-Type: application/json

{ "name": "Korona Duńska", "code": "DK", "isCrypto": 0 }

### Remove currency
DELETE http://{{hostname}}:{{port}}/api/rates/exchange-rates/1
Accept: application/json
Content-Type: application/json

###